# -*- coding: utf-8 -*-
"""ComputeDistance&TimeMatrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L93T-AXYUlCBKAf-URM0aGKugL9JTZLA
"""

import pandas as pd
import numpy as np
import requests
import json
import datetime
import os
import time
from google.colab import userdata

from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

try:
    API_KEY = userdata.get('GOOGLE_API_KEY')
    if not API_KEY:
        raise ValueError("API key is empty. Please check your Colab Secrets.")
except userdata.SecretNotFoundError:
    print("Error: 'GOOGLE_API_KEY' secret not found.")
    API_KEY = None
except ValueError as e:
    print(e)
    API_KEY = None


CSV_INPUT_FILE = "Monday_Customers.csv"
PLACE_ID_COLUMN_NAME = "place_id"
API_URL = "https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix"

# Output Files
OUTPUT_DISTANCE_MATRIX_FILE = "Monday_Customers_distance_matrix.csv"
OUTPUT_DURATION_MATRIX_FILE = "Monday_Customers_duration_matrix.csv"

# Checkpoint files
CHECKPOINT_DISTANCE_FILE = "distance_matrix.npy"
CHECKPOINT_DURATION_FILE = "duration_matrix.npy"

API_CHUNK_SIZE = 10


# Read the location data from the CSV file
def read_locations_from_csv(csv_file, place_id_col):

    try:
        df = pd.read_csv(csv_file)
    except FileNotFoundError:
        print(f"ERROR: CSV file not found at '{csv_file}'")
        return None, 0
    if place_id_col not in df.columns:
        print(f"ERROR: Column '{place_id_col}' not found in CSV.")
        return None, 0
    waypoints = [{"waypoint": {"placeId": str(pid)}} for pid in df[place_id_col]]
    num_locations = len(waypoints)
    print(f"Successfully read {num_locations} locations from '{csv_file}'.")
    print(f"Depot (Index 0) Place ID: {df[place_id_col].iloc[0]}")
    return waypoints, num_locations

# Create a requests.Session with automatic retries on server errors
def setup_session_with_retries():
    session = requests.Session()
    retries = Retry(total=3, backoff_factor=1, status_forcelist=[500, 502, 503, 504], allowed_methods=["POST"])
    session.mount("https://", HTTPAdapter(max_retries=retries))
    return session

#Calls the Google Routes API
def call_routes_api(session, request_body, api_key):

    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": api_key,
        "X-Goog-FieldMask": "originIndex,destinationIndex,duration,distanceMeters,status"
    }
    num_origins = len(request_body['origins'])
    num_dests = len(request_body['destinations'])
    print(f"  > Calling API for {num_origins}x{num_dests} sub-matrix...")

    try:
        response = session.post(API_URL, data=json.dumps(request_body), headers=headers)
        response.raise_for_status()
        response_data = response.json()
        print(f"  > API call successful. Received {len(response_data)} matrix elements.")

        # 2-second pause
        print("  > Pausing for 2s to respect rate limit...")
        time.sleep(2)

        return response_data

    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
        print(f"Response content: {response.text}")
        if "API key not valid" in response.text:
            print("\n FAILED: CHECK API KEY ")
        if "has not been used" in response.text:
            print("\n FAILED: ENABLE 'Routes API' IN GOOGLE CLOUD CONSOLE")
        if response.status_code == 429:
             print("\n FAILED: 429 'Too Many Requests' / 'Resource Exhausted' ")
    except requests.exceptions.RequestException as req_err:
        print(f" Error occurred (retries may have failed): {req_err}")

    return None

#Parse the API response and update the main matrices
def populate_matrices_from_response(response_data, distance_matrix, duration_matrix, origin_offset, dest_offset):

    elements_populated = 0
    for element in response_data:
        if 'originIndex' in element:
            local_origin_idx = element['originIndex']
            local_dest_idx = element['destinationIndex']

            # This check correctly handles self-to-self (e.g., [0,0])
            if local_origin_idx == local_dest_idx and origin_offset == dest_offset:
                distance_meters = 0
                duration_seconds = 0
            else:
                distance_meters = element.get('distanceMeters', 0)
                duration_str = element.get('duration', '0s')
                duration_seconds = int(duration_str.rstrip('s'))

            global_origin_idx = local_origin_idx + origin_offset
            global_dest_idx = local_dest_idx + dest_offset

            distance_matrix[global_origin_idx, global_dest_idx] = distance_meters
            duration_matrix[global_origin_idx, global_dest_idx] = duration_seconds
            elements_populated += 1
        else:
            status_msg = element.get('status', {}).get('message', 'Unknown error')
            print(f"  > WARNING: No route found for an element in this chunk. Status: {status_msg}")
    print(f"  > Populated {elements_populated} elements in the main matrices.")

#Save the matrices for checkpointing
def save_matrices_to_npy(distance_matrix, duration_matrix):

    np.save(CHECKPOINT_DISTANCE_FILE, distance_matrix)
    np.save(CHECKPOINT_DURATION_FILE, duration_matrix)
    print("  > Checkpoint saved.")

#Save the final matrices to CSV files
def save_matrices_to_csv(distance_matrix, duration_matrix):

    np.savetxt(OUTPUT_DISTANCE_MATRIX_FILE, distance_matrix, delimiter=',', fmt='%d')
    print(f"Distance matrix saved to '{OUTPUT_DISTANCE_MATRIX_FILE}'")
    np.savetxt(OUTPUT_DURATION_MATRIX_FILE, duration_matrix, delimiter=',', fmt='%d')
    print(f"Duration matrix saved to '{OUTPUT_DURATION_MATRIX_FILE}'")

def main():
    if not API_KEY:
        print(" ERROR: 'GOOGLE_API_KEY' secret not found or is empty. Exiting. ")
        return

    locations, num_loc = read_locations_from_csv(CSV_INPUT_FILE, PLACE_ID_COLUMN_NAME)
    if not locations:
        return

    print(f"\nPreparing to build a {num_loc}x{num_loc} matrix using {API_CHUNK_SIZE}x{API_CHUNK_SIZE} chunks.")

    now = datetime.datetime.now(datetime.timezone.utc)
    tomorrow = now + datetime.timedelta(days=1)
    departure_time = tomorrow.replace(hour=8, minute=0, second=0, microsecond=0)
    departure_time_str = departure_time.isoformat().replace("+00:00", "Z")
    print(f"Using predictive departure time: {departure_time_str}")

    api_session = setup_session_with_retries()

    # Load from checkpoint or create new matrices
    try:
        distance_matrix = np.load(CHECKPOINT_DISTANCE_FILE)
        duration_matrix = np.load(CHECKPOINT_DURATION_FILE)
        print(f" Loaded matrices from checkpoint files ")
        if distance_matrix.shape != (num_loc, num_loc):
             raise ValueError("Checkpoint shape mismatch. Starting fresh.")
    except (FileNotFoundError, ValueError) as e:
        print(f" No valid checkpoint found ({e}). Creating new matrices. ")
        distance_matrix = np.zeros((num_loc, num_loc), dtype=int)
        duration_matrix = np.zeros((num_loc, num_loc), dtype=int)

    # Loop through the matrix in chunks
    for i in range(0, num_loc, API_CHUNK_SIZE):
        origin_start = i
        origin_end = min(i + API_CHUNK_SIZE, num_loc)
        origin_chunk = locations[origin_start:origin_end]

        for j in range(0, num_loc, API_CHUNK_SIZE):
            dest_start = j
            dest_end = min(j + API_CHUNK_SIZE, num_loc)
            dest_chunk = locations[dest_start:dest_end]

            print(f"\n Processing Chunk ")
            print(f"Origins:      {origin_start} to {origin_end-1}")
            print(f"Destinations: {dest_start} to {dest_end-1}")

            # Resume logic: Check if the first element of this chunk is populated
            # Also check that it's not a diagonal chunk (which starts with 0)
            if origin_start != dest_start and distance_matrix[origin_start, dest_start] != 0:
                print(f"  > Skipping chunk, data already populated from checkpoint.")
                continue

            body = {
                "origins": origin_chunk,
                "destinations": dest_chunk,
                "travelMode": "DRIVE",
                "routingPreference": "TRAFFIC_AWARE_OPTIMAL",
                "departureTime": departure_time_str
            }

            api_response = call_routes_api(api_session, body, API_KEY)

            if not api_response:
                print(f"ERROR: API call failed for chunk (Origins {origin_start}-{origin_end}, Dests {dest_start}-{dest_end}).")
                print("Stopping script. Re-run to resume from this chunk.")
                return

            populate_matrices_from_response(api_response,
                                            distance_matrix,
                                            duration_matrix,
                                            origin_start,
                                            dest_start)

            # Save to checkpoint files after every successful chunk
            save_matrices_to_npy(distance_matrix, duration_matrix)

    print("\n All chunks processed ")
    save_matrices_to_csv(distance_matrix, duration_matrix)

    print("\n SCRIPT FINISHED SUCCESSFULLY ")

if __name__ == "__main__":
    main()