# -*- coding: utf-8 -*-
"""Geocoding Script for Google Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hv4fia8g-oRjFH32hO0z4SK8y8WVBcWh
"""

import pandas as pd
import requests
import json
from google.colab import userdata

try:
    API_KEY = userdata.get('GOOGLE_API_KEY')
    if not API_KEY:
        raise ValueError("API key is empty.")
except (userdata.SecretNotFoundError, ValueError) as e:
    print(f"Setup Error: {e}. Please ensure 'GOOGLE_API_KEY' is set in Colab Secrets.")
    API_KEY = None

addresses_to_geocode = [
    "Schulstrasse 8, Lanterswil 9503",
    "obere Bahnhofstrasse 58, Rapperswil 8640",
    "Schlipfstrasse 12, Wald 8636",
    "Gwattstrasse 7a, Pfäffikon SZ 8808",
    "Bahnhofwiese 11, Stäfa 8712",
    "Bahnhofstrasse 22, Stäfa 8712",
    "Schulhausstrasse 18, Meilen 8706",
    "Seefeldstrasse 29, Zürich 8008",
    "Falkenstrasse 12, Zürich 8008",
    "Stockerstrasse 38, Zürich 8002",
    "Badenerstrasse 171, Zürich 8004",
    "Bremgartenstrasse 18, Zürich 8003",
    "Altstetterstrasse 128, Zürich 8048",
    "Ginsterstrasse 1, Albisrieden 8047",
    "Birmensdorferstrasse 145, Zürich 8003",
    "Hauptstrasse 29, Tobel 9555",
    "Althoossteig 2, Zürich 8046",
    "Saatlenstrasse 12, Zürich 8051",
    "Hardturmstrasse 171, Zürich 8005",
    "Aargauerstrasse 1, Zürich 8048",
    "Zweierstrasse 56, Zürich 8004",
    "Kirchgasse 4, Zürich 8001",
    "Asylstrasse 70, Zürich 8032",
    "Römerhofplatz 5, Zürich 8032",
    "Toblerstrasse 51, Zürich 8044",
    "Voltastrasse 40, Zürich 8044",
    "Nordstrasse 227, Zürich 8037",
    "Röschlibachstrassse 79, Zürich 8037",
    "Hardturmstrasse 66, Zürich 8005",
    "Limmatstrasse 231, Zürich 8005",
    "Nordstrasse 89, Zürich 8037",
    "Nordstrasse 88, Zürich 8037",
    "Lettensteg 10, Zürich 8005",
    "Mythenquai 95, Zürich 8002",
    "Seestrasse 205, Kilchberg 8802",
    "Hardstrasse 210, Zürich 8005",
    "Halle Löwenstrasse, Zürich 8001",
    "Freischützstrasse 1a, Zürich 8004",
    "Bahnhofstrasse 88, Zürich 8001",
    "Sonnenhofstrasse 2, Wil 9500"
]

geocoded_results = []


# Queries Google Maps Geocoding API. Returns a dictionary with coordinates or empty fields on failure.
def geocode_address(address, api_key):
    endpoint = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        'address': address,
        'key': api_key
    }

    try:
        response = requests.get(endpoint, params=params)
        response.raise_for_status() # halting on 4xx/5xx errors
        data = response.json()

        # Checking the internal 'status'
        if data['status'] == 'OK':
            result = data['results'][0]

            if len(data['results']) > 1:
                print(f"Warning: Ambiguous address '{address}'. Defaulting to first result.")

            return {
                "original_query": address,
                "formatted_address": result.get('formatted_address'),
                "place_id": result.get('place_id'),
                "latitude": result.get('geometry', {}).get('location', {}).get('lat'),
                "longitude": result.get('geometry', {}).get('location', {}).get('lng'),
                "status": data['status'],
                "result_count": len(data['results'])
            }

        # Handling ZERO_RESULTS, REQUEST_DENIED, or OVER_QUERY_LIMIT
        else:
            return {
                "original_query": address,
                "formatted_address": None,
                "place_id": None,
                "latitude": None,
                "longitude": None,
                "status": data['status'],
                "result_count": 0
            }

    except Exception as e:
        print(f"Exception during request for '{address}': {e}")
        return {
            "original_query": address,
            "status": "ERROR",
            "error_message": str(e)
        }

if API_KEY:
    print(f"Processing {len(addresses_to_geocode)} addresses...\n")

    for address in addresses_to_geocode:
        print(f"Geocoding: '{address}'")
        result_data = geocode_address(address, API_KEY)
        geocoded_results.append(result_data)

    print("\n--- Processing Complete ---")

    # Dumps the raw JSON to the console for verification
    print(json.dumps(geocoded_results, indent=2))

    # 1. Exports to JSON (preserves structure/metadata)
    json_filename = 'geocoded_locations.json'
    with open(json_filename, 'w') as f:
        json.dump(geocoded_results, f, indent=2)
    print(f"Saved: {json_filename}")

    # 2. Exports to CSV (flat format for tabular analysis)
    csv_filename = 'geocoded_locations.csv'
    try:
        df = pd.DataFrame(geocoded_results)
        df.to_csv(csv_filename, index=False)
        print(f"Saved: {csv_filename}")
    except Exception as e:
        print(f"CSV Export Failed: {e}")

else:
    print("Aborting: API Key missing.")