# -*- coding: utf-8 -*-
"""Solving_vrptw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBADJXrjE1ijCOOXFPk0ZrtR4awo0SMS

##### Copyright 2025 Google LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

# vrp_time_windows

<table align="left">
<td>
<a href="https://colab.research.google.com/github/google/or-tools/blob/main/examples/notebook/constraint_solver/vrp_time_windows.ipynb"><img src="https://raw.githubusercontent.com/google/or-tools/main/tools/colab_32px.png"/>Run in Google Colab</a>
</td>
<td>
<a href="https://github.com/google/or-tools/blob/main/ortools/constraint_solver/samples/vrp_time_windows.py"><img src="https://raw.githubusercontent.com/google/or-tools/main/tools/github_32px.png"/>View source on GitHub</a>
</td>
</table>

First, you must install [ortools](https://pypi.org/project/ortools/) package in this colab.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ortools

"""
Vehicles Routing Problem (VRP) with Time Windows.
"""

from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp
import pandas as pd
from datetime import datetime, timedelta
from IPython.display import display, HTML

#reads duration matrix from a csv file and creates data model
def create_data_model():

    data = {}
    raw_matrix = [
    [0.0, 3644.0, 3883.0, 4097.0, 4319.0, 4160.0, 3589.0, 3500.0, 3404.0, 3312.0, 3371.0, 3554.0, 3325.0, 3455.0, 501.0, 2940.0, 2789.0, 3017.0, 3180.0, 3347.0, 3468.0, 3392.0, 3273.0, 3103.0, 3104.0, 2953.0, 2975.0, 2906.0, 3067.0, 2960.0, 3034.0, 2574.0, 2968.0, 3114.0, 3129.0, 3327.0, 3302.0, 702.0],
    [3577.0, 0.0, 395.0, 786.0, 727.0, 1197.0, 2355.0, 2396.0, 2041.0, 2083.0, 2046.0, 2697.0, 2472.0, 2027.0, 3495.0, 2711.0, 2496.0, 2523.0, 2584.0, 2020.0, 2383.0, 2146.0, 2255.0, 2364.0, 2404.0, 2436.0, 2463.0, 2542.0, 2393.0, 2494.0, 2417.0, 1839.0, 1478.0, 2410.0, 2386.0, 1980.0, 2260.0, 3155.0],
    [3835.0, 563.0, 0.0, 1314.0, 1261.0, 1738.0, 2172.0, 2222.0, 1854.0, 1894.0, 1859.0, 2490.0, 2282.0, 1830.0, 3773.0, 2532.0, 2619.0, 2332.0, 2386.0, 1830.0, 2174.0, 2365.0, 2450.0, 2539.0, 2468.0, 2257.0, 2281.0, 2356.0, 2221.0, 2291.0, 2253.0, 1661.0, 1295.0, 2218.0, 2198.0, 1794.0, 2071.0, 3399.0],
    [4142.0, 793.0, 1178.0, 0.0, 63.0, 639.0, 2067.0, 2135.0, 2276.0, 2668.0, 2635.0, 3244.0, 3026.0, 2590.0, 3933.0, 2705.0, 2299.0, 2920.0, 3117.0, 2549.0, 2184.0, 1952.0, 2074.0, 2173.0, 2213.0, 2634.0, 2627.0, 2803.0, 2716.0, 2668.0, 2622.0, 2335.0, 2244.0, 2970.0, 2511.0, 2502.0, 2637.0, 3688.0],
    [4119.0, 825.0, 1188.0, 223.0, 0.0, 663.0, 2078.0, 2139.0, 2286.0, 2686.0, 2625.0, 3160.0, 3010.0, 2601.0, 3999.0, 2795.0, 2383.0, 2915.0, 3111.0, 2530.0, 2180.0, 2026.0, 2146.0, 2268.0, 2291.0, 2788.0, 2792.0, 2801.0, 2702.0, 2665.0, 2614.0, 2358.0, 2280.0, 2991.0, 2495.0, 2520.0, 2649.0, 3720.0],
    [4065.0, 1314.0, 1673.0, 748.0, 648.0, 0.0, 1554.0, 1625.0, 1771.0, 2163.0, 2120.0, 2726.0, 2528.0, 2090.0, 3783.0, 2575.0, 2170.0, 2389.0, 2617.0, 2036.0, 1666.0, 1661.0, 1766.0, 1911.0, 1959.0, 2275.0, 2272.0, 2311.0, 2177.0, 2160.0, 2102.0, 1834.0, 2214.0, 2481.0, 1990.0, 1996.0, 2109.0, 3854.0],
    [3364.0, 2239.0, 2088.0, 1873.0, 1890.0, 1348.0, 0.0, 146.0, 507.0, 908.0, 870.0, 1486.0, 1296.0, 831.0, 3147.0, 1371.0, 1253.0, 1176.0, 1405.0, 725.0, 427.0, 392.0, 480.0, 684.0, 685.0, 1050.0, 1042.0, 1065.0, 966.0, 937.0, 852.0, 559.0, 965.0, 1174.0, 733.0, 729.0, 886.0, 3219.0],
    [3238.0, 2064.0, 1954.0, 2004.0, 1977.0, 1445.0, 170.0, 0.0, 350.0, 707.0, 722.0, 1346.0, 1148.0, 679.0, 2983.0, 1224.0, 1102.0, 1039.0, 1243.0, 615.0, 249.0, 444.0, 515.0, 615.0, 543.0, 905.0, 893.0, 910.0, 810.0, 789.0, 699.0, 402.0, 807.0, 1038.0, 598.0, 545.0, 731.0, 3063.0],
    [3184.0, 1831.0, 1705.0, 2120.0, 2022.0, 1472.0, 385.0, 439.0, 0.0, 374.0, 474.0, 1052.0, 830.0, 419.0, 2922.0, 1086.0, 951.0, 851.0, 924.0, 326.0, 375.0, 551.0, 633.0, 733.0, 659.0, 793.0, 812.0, 795.0, 670.0, 673.0, 590.0, 237.0, 647.0, 747.0, 539.0, 207.0, 413.0, 3005.0],
    [3039.0, 1869.0, 1752.0, 2461.0, 2381.0, 1832.0, 758.0, 806.0, 389.0, 0.0, 267.0, 683.0, 469.0, 394.0, 2773.0, 748.0, 827.0, 527.0, 607.0, 158.0, 755.0, 867.0, 953.0, 951.0, 961.0, 448.0, 466.0, 548.0, 410.0, 539.0, 442.0, 560.0, 967.0, 413.0, 622.0, 196.0, 491.0, 2869.0],
    [3120.0, 1776.0, 1645.0, 2409.0, 2350.0, 1805.0, 734.0, 796.0, 416.0, 159.0, 0.0, 769.0, 465.0, 236.0, 2868.0, 835.0, 911.0, 603.0, 682.0, 238.0, 741.0, 921.0, 998.0, 1098.0, 1030.0, 525.0, 548.0, 628.0, 489.0, 623.0, 522.0, 452.0, 859.0, 495.0, 701.0, 284.0, 579.0, 2948.0],
    [3347.0, 2496.0, 2407.0, 3176.0, 3117.0, 2611.0, 1562.0, 1669.0, 1185.0, 891.0, 847.0, 0.0, 545.0, 999.0, 3184.0, 1064.0, 1246.0, 630.0, 468.0, 1016.0, 1566.0, 1563.0, 1660.0, 1368.0, 1368.0, 862.0, 888.0, 656.0, 814.0, 1051.0, 852.0, 1293.0, 1717.0, 693.0, 1193.0, 1038.0, 1248.0, 3222.0],
    [3221.0, 2157.0, 2031.0, 2828.0, 2762.0, 2221.0, 1203.0, 1257.0, 884.0, 572.0, 435.0, 501.0, 0.0, 537.0, 3012.0, 1010.0, 1089.0, 731.0, 559.0, 657.0, 1205.0, 1363.0, 1450.0, 1195.0, 1214.0, 699.0, 731.0, 764.0, 661.0, 951.0, 697.0, 928.0, 1330.0, 674.0, 1031.0, 697.0, 985.0, 3097.0],
    [3176.0, 1823.0, 1705.0, 2482.0, 2434.0, 1877.0, 825.0, 880.0, 508.0, 243.0, 88.0, 847.0, 436.0, 0.0, 2925.0, 913.0, 992.0, 685.0, 764.0, 332.0, 829.0, 1005.0, 1084.0, 1113.0, 1113.0, 605.0, 632.0, 709.0, 569.0, 708.0, 608.0, 539.0, 950.0, 578.0, 797.0, 360.0, 665.0, 3023.0],
    [517.0, 3580.0, 3843.0, 3888.0, 3958.0, 3952.0, 3505.0, 3416.0, 3340.0, 3273.0, 3320.0, 3489.0, 3295.0, 3398.0, 0.0, 2811.0, 2570.0, 2904.0, 3068.0, 3278.0, 3367.0, 3322.0, 3038.0, 2908.0, 2918.0, 2848.0, 2870.0, 2784.0, 2950.0, 2849.0, 2926.0, 3520.0, 3887.0, 3027.0, 3038.0, 3302.0, 3244.0, 647.0],
    [3031.0, 2776.0, 2694.0, 2609.0, 2671.0, 2545.0, 1511.0, 1378.0, 1356.0, 1244.0, 1048.0, 1163.0, 1236.0, 1349.0, 2759.0, 0.0, 784.0, 773.0, 863.0, 1328.0, 1359.0, 1160.0, 1082.0, 809.0, 816.0, 623.0, 646.0, 544.0, 698.0, 678.0, 731.0, 1562.0, 1942.0, 809.0, 924.0, 1249.0, 1187.0, 2829.0],
    [2772.0, 2605.0, 2716.0, 2203.0, 2256.0, 2045.0, 1433.0, 1337.0, 1344.0, 1192.0, 1373.0, 1563.0, 1365.0, 1457.0, 2508.0, 739.0, 0.0, 893.0, 1079.0, 1235.0, 1289.0, 1105.0, 1110.0, 812.0, 817.0, 834.0, 860.0, 759.0, 894.0, 788.0, 865.0, 1488.0, 1871.0, 1028.0, 974.0, 1241.0, 1186.0, 2579.0],
    [3001.0, 2427.0, 2319.0, 2626.0, 2687.0, 2346.0, 1316.0, 1234.0, 1096.0, 808.0, 875.0, 617.0, 693.0, 1042.0, 2785.0, 727.0, 801.0, 0.0, 300.0, 924.0, 1190.0, 1107.0, 1192.0, 943.0, 940.0, 438.0, 461.0, 140.0, 374.0, 586.0, 409.0, 1214.0, 1632.0, 304.0, 741.0, 947.0, 966.0, 2847.0],
    [3023.0, 2396.0, 2273.0, 2641.0, 2689.0, 2485.0, 1404.0, 1275.0, 1080.0, 782.0, 853.0, 611.0, 643.0, 776.0, 2782.0, 757.0, 830.0, 222.0, 0.0, 899.0, 1236.0, 1187.0, 1224.0, 966.0, 971.0, 451.0, 472.0, 271.0, 412.0, 699.0, 447.0, 1175.0, 1573.0, 295.0, 774.0, 924.0, 973.0, 2866.0],
    [3131.0, 1761.0, 1640.0, 2410.0, 2340.0, 1803.0, 727.0, 796.0, 398.0, 145.0, 158.0, 797.0, 523.0, 282.0, 2885.0, 861.0, 938.0, 634.0, 712.0, 0.0, 738.0, 915.0, 988.0, 1088.0, 1021.0, 549.0, 573.0, 656.0, 517.0, 527.0, 550.0, 444.0, 853.0, 525.0, 609.0, 178.0, 483.0, 2972.0],
    [3210.0, 2036.0, 1895.0, 1996.0, 1914.0, 1362.0, 254.0, 307.0, 302.0, 653.0, 679.0, 1315.0, 1107.0, 636.0, 2970.0, 1206.0, 986.0, 1034.0, 1221.0, 565.0, 0.0, 437.0, 515.0, 613.0, 533.0, 891.0, 886.0, 898.0, 807.0, 782.0, 686.0, 360.0, 770.0, 1051.0, 591.0, 493.0, 589.0, 3039.0],
    [3274.0, 2248.0, 2323.0, 1879.0, 1942.0, 1553.0, 541.0, 430.0, 758.0, 1022.0, 1145.0, 1636.0, 1443.0, 1108.0, 3059.0, 1261.0, 1147.0, 1110.0, 1284.0, 952.0, 591.0, 0.0, 232.0, 417.0, 434.0, 943.0, 941.0, 980.0, 895.0, 818.0, 773.0, 814.0, 1219.0, 1116.0, 665.0, 849.0, 880.0, 3141.0],
    [3164.0, 2222.0, 2272.0, 1862.0, 1917.0, 1533.0, 506.0, 394.0, 701.0, 948.0, 1065.0, 1676.0, 1464.0, 1027.0, 2929.0, 1092.0, 966.0, 1042.0, 1219.0, 889.0, 542.0, 36.0, 0.0, 308.0, 334.0, 780.0, 775.0, 906.0, 819.0, 764.0, 706.0, 749.0, 1146.0, 1054.0, 607.0, 785.0, 823.0, 3012.0],
    [2921.0, 2468.0, 2421.0, 2096.0, 2160.0, 1917.0, 852.0, 636.0, 849.0, 981.0, 1054.0, 1350.0, 1286.0, 1174.0, 2647.0, 804.0, 667.0, 819.0, 1015.0, 919.0, 607.0, 336.0, 353.0, 0.0, 101.0, 502.0, 498.0, 690.0, 637.0, 440.0, 625.0, 912.0, 1298.0, 942.0, 508.0, 807.0, 735.0, 2736.0],
    [2943.0, 2501.0, 2391.0, 2136.0, 2191.0, 1878.0, 796.0, 674.0, 791.0, 930.0, 994.0, 1378.0, 1311.0, 1110.0, 2679.0, 821.0, 689.0, 832.0, 1030.0, 860.0, 535.0, 327.0, 351.0, 84.0, 0.0, 523.0, 517.0, 709.0, 645.0, 462.0, 576.0, 846.0, 1236.0, 928.0, 440.0, 757.0, 616.0, 2762.0],
    [2763.0, 2359.0, 2288.0, 2331.0, 2384.0, 2134.0, 1125.0, 1018.0, 955.0, 654.0, 845.0, 860.0, 813.0, 936.0, 2491.0, 416.0, 489.0, 316.0, 510.0, 716.0, 984.0, 779.0, 807.0, 518.0, 526.0, 0.0, 24.0, 190.0, 347.0, 258.0, 324.0, 1154.0, 1564.0, 456.0, 563.0, 757.0, 791.0, 2579.0],
    [2817.0, 2472.0, 2386.0, 2370.0, 2446.0, 2194.0, 1112.0, 1017.0, 942.0, 698.0, 780.0, 916.0, 903.0, 1030.0, 2554.0, 463.0, 539.0, 399.0, 594.0, 751.0, 937.0, 880.0, 952.0, 691.0, 689.0, 166.0, 0.0, 276.0, 365.0, 323.0, 390.0, 1090.0, 1478.0, 476.0, 552.0, 834.0, 774.0, 2623.0],
    [2888.0, 2424.0, 2318.0, 2486.0, 2541.0, 2201.0, 1185.0, 1117.0, 1001.0, 708.0, 887.0, 639.0, 671.0, 1039.0, 2657.0, 597.0, 681.0, 135.0, 332.0, 771.0, 1060.0, 984.0, 1061.0, 823.0, 827.0, 318.0, 344.0, 0.0, 245.0, 464.0, 275.0, 1209.0, 1610.0, 284.0, 606.0, 809.0, 830.0, 2732.0],
    [2905.0, 2215.0, 2118.0, 2514.0, 2637.0, 2081.0, 1035.0, 961.0, 763.0, 500.0, 667.0, 869.0, 865.0, 782.0, 2613.0, 557.0, 630.0, 353.0, 544.0, 559.0, 896.0, 830.0, 901.0, 770.0, 777.0, 254.0, 278.0, 229.0, 0.0, 310.0, 105.0, 907.0, 1309.0, 283.0, 452.0, 597.0, 596.0, 2696.0],
    [2796.0, 2340.0, 2239.0, 2348.0, 2428.0, 2040.0, 1040.0, 936.0, 856.0, 557.0, 721.0, 974.0, 969.0, 839.0, 2526.0, 567.0, 506.0, 470.0, 665.0, 614.0, 870.0, 740.0, 767.0, 482.0, 486.0, 168.0, 163.0, 349.0, 256.0, 0.0, 220.0, 1011.0, 1392.0, 531.0, 473.0, 660.0, 696.0, 2605.0],
    [2873.0, 2231.0, 2162.0, 2416.0, 2555.0, 1970.0, 934.0, 859.0, 738.0, 481.0, 646.0, 855.0, 721.0, 767.0, 2584.0, 542.0, 617.0, 337.0, 536.0, 542.0, 806.0, 722.0, 808.0, 653.0, 657.0, 240.0, 263.0, 213.0, 134.0, 209.0, 0.0, 880.0, 1288.0, 359.0, 348.0, 582.0, 581.0, 2668.0],
    [3450.0, 1805.0, 1691.0, 2284.0, 2176.0, 1606.0, 519.0, 574.0, 330.0, 627.0, 593.0, 1229.0, 1018.0, 543.0, 3272.0, 1276.0, 1344.0, 1068.0, 1124.0, 485.0, 518.0, 694.0, 775.0, 874.0, 799.0, 976.0, 1002.0, 1082.0, 930.0, 943.0, 902.0, 0.0, 417.0, 946.0, 834.0, 441.0, 730.0, 3328.0],
    [3838.0, 1615.0, 1482.0, 2347.0, 2277.0, 2080.0, 991.0, 1042.0, 809.0, 1096.0, 1055.0, 1675.0, 1458.0, 1015.0, 3676.0, 1726.0, 1803.0, 1501.0, 1566.0, 961.0, 991.0, 1175.0, 1251.0, 1347.0, 1275.0, 1427.0, 1450.0, 1533.0, 1393.0, 1402.0, 1363.0, 513.0, 0.0, 1395.0, 1301.0, 919.0, 1198.0, 3735.0],
    [3011.0, 2460.0, 2356.0, 2573.0, 2643.0, 2300.0, 1284.0, 1208.0, 1035.0, 830.0, 770.0, 782.0, 852.0, 984.0, 2749.0, 689.0, 774.0, 363.0, 445.0, 869.0, 1150.0, 1081.0, 1154.0, 905.0, 909.0, 396.0, 419.0, 367.0, 303.0, 553.0, 368.0, 1232.0, 1615.0, 0.0, 701.0, 873.0, 871.0, 2827.0],
    [3050.0, 1953.0, 1846.0, 2384.0, 2309.0, 1752.0, 680.0, 733.0, 399.0, 420.0, 555.0, 1140.0, 936.0, 584.0, 2809.0, 997.0, 833.0, 755.0, 887.0, 414.0, 674.0, 702.0, 784.0, 796.0, 725.0, 649.0, 654.0, 631.0, 502.0, 512.0, 474.0, 548.0, 956.0, 703.0, 0.0, 279.0, 245.0, 2889.0],
    [3137.0, 1825.0, 1686.0, 2296.0, 2236.0, 1662.0, 583.0, 632.0, 312.0, 185.0, 264.0, 848.0, 630.0, 387.0, 2886.0, 911.0, 909.0, 672.0, 754.0, 114.0, 582.0, 691.0, 773.0, 851.0, 774.0, 600.0, 626.0, 695.0, 491.0, 501.0, 459.0, 448.0, 855.0, 574.0, 466.0, 0.0, 349.0, 2967.0],
    [2930.0, 2020.0, 1896.0, 2365.0, 2294.0, 1737.0, 652.0, 665.0, 462.0, 528.0, 611.0, 1193.0, 987.0, 631.0, 2650.0, 821.0, 652.0, 631.0, 834.0, 468.0, 632.0, 531.0, 613.0, 583.0, 559.0, 530.0, 551.0, 507.0, 414.0, 439.0, 304.0, 592.0, 999.0, 652.0, 200.0, 357.0, 0.0, 2728.0],
    [698.0, 3115.0, 3331.0, 3673.0, 3712.0, 3830.0, 3453.0, 3371.0, 3327.0, 3193.0, 3289.0, 3408.0, 3240.0, 3311.0, 544.0, 2737.0, 2500.0, 2828.0, 2991.0, 3203.0, 3305.0, 3303.0, 2978.0, 2847.0, 2858.0, 2776.0, 2797.0, 2705.0, 2878.0, 2785.0, 2851.0, 3450.0, 3829.0, 2955.0, 2970.0, 3247.0, 3175.0, 0.0]
]

    # Cast matrix to Integers
    data["time_matrix"] = [[int(x) for x in row] for row in raw_matrix]

    #Hardcoded time windows
    data["time_windows"] = [
    (0, 52800), # 0. 4:20 to 19:00
    (0, 15000), # 1.  8:30
    (0, 13200), # 2.  8:00
    (0, 16800), # 3.  9:00
    (0, 6000),  # 4.  6:00
    (0, 7800),  # 5.  6:30
    (0, 13200), # 6.  8:00
    (0, 52800), # 7.  TK 19:00 (7:00 PM)
    (0, 13200), # 8.  8:00
    (0, 13200), # 9. 8:00
    (0, 52800), # 10. TK 19:00 (7:00 PM)
    (0, 16800), # 11. 9:00
    (0, 13200), # 12. 8:00
    (0, 13200), # 13. 8:00
    (0, 3300),  # 14. 5:15
    (0, 16800), # 15. 9:00
    (0, 16800), # 16. 9:00
    (0, 13200), # 17. 8:00
    (0, 6000),  # 18. Originally 5:00; Extended to 6:00 AM
    (0, 9600),  # 19. 7:00
    (0, 7800),  # 20. 6:30
    (0, 25800), # 21. 11:30
    (0, 11400), # 22. 7:30
    (0, 52800), # 23. 19:00 (7:00 PM)
    (0, 9000),  # 24. 6:50
    (0, 9600),  # 25. 7:00
    (0, 52800), # 26. TK 19:00 (7:00 PM)
    (0, 13200), # 27. 8:00
    (0, 13200), # 28. 8:00
    (11400, 13200) ,# 29. "7:30 to 8:00 AM" (Strict Window)
    (13200, 16800), # 30. "8:00 to 9:00 AM" (Not before 8:00 and 9 is opening time)
    (0, 52800), # 31. TK 19:00 (7:00 PM)
    (0, 52800), # 32. TK 19:00 (7:00 PM)
    (0, 52800), # 33. TK 19:00 (7:00 PM)
    (0, 52800), # 34. TK 19:00 (7:00 PM)
    (0, 52800), # 35. TK 19:00 (7:00 PM)
    (0, 52800), # 36. TK 19:00 (7:00 PM)
    (0, 16800)  # 37. 9:00
]
    data["num_vehicles"] = 2
    data["depot"] = 0
    return data


#Displays solution with Waiting Time (Slack)
def print_solution_with_slack(data, manager, routing, solution):
    base_time = datetime(2025, 1, 1, 4, 20, 0)
    schedule_data = {}
    time_dimension = routing.GetDimensionOrDie("Time")


    print(f"Objective Value: {solution.ObjectiveValue()}")

    for vehicle_id in range(data["num_vehicles"]):
        index = routing.Start(vehicle_id)
        prev_index = index # Keep track of previous node

        col_nodes = []
        col_times = []
        col_waits = []

        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            time_var = time_dimension.CumulVar(index)
            current_seconds = solution.Min(time_var)

            # Calculating wait time
            wait_time_min = 0
            if index != routing.Start(vehicle_id):
                # previous time
                prev_time_var = time_dimension.CumulVar(prev_index)
                prev_seconds = solution.Min(prev_time_var)

                # travel time
                prev_node = manager.IndexToNode(prev_index)
                curr_node = manager.IndexToNode(index)
                travel_seconds = data["time_matrix"][prev_node][curr_node]

                # Calculating Arrival
                arrival_seconds = prev_seconds + travel_seconds

                # Wait = Start - Arrival
                wait_seconds = current_seconds - arrival_seconds
                wait_time_min = int(wait_seconds / 60) # Convert to minutes


            clock_time = base_time + timedelta(seconds=int(current_seconds))

            col_nodes.append(node_index)
            col_times.append(clock_time.strftime("%H:%M"))
            # Show wait only if it exists
            col_waits.append(f"{wait_time_min} min" if wait_time_min > 0 else "-")


            prev_index = index
            index = solution.Value(routing.NextVar(index))

        # Depot Return
        node_index = manager.IndexToNode(index)
        time_var = time_dimension.CumulVar(index)
        current_seconds = solution.Min(time_var)

        # Calculating wait at end
        prev_time_var = time_dimension.CumulVar(prev_index)
        prev_seconds = solution.Min(prev_time_var)
        prev_node = manager.IndexToNode(prev_index)
        curr_node = manager.IndexToNode(index)
        travel_seconds = data["time_matrix"][prev_node][curr_node]
        arrival_seconds = prev_seconds + travel_seconds
        wait_seconds = current_seconds - arrival_seconds
        wait_time_min = int(wait_seconds / 60)

        clock_time = base_time + timedelta(seconds=int(current_seconds))

        col_nodes.append(node_index)
        col_times.append(clock_time.strftime("%H:%M"))
        col_waits.append(f"{wait_time_min} min" if wait_time_min > 0 else "-")

        # Store Columns
        schedule_data[f"V{vehicle_id} Node"] = pd.Series(col_nodes)
        schedule_data[f"V{vehicle_id} Time"] = pd.Series(col_times)
        schedule_data[f"V{vehicle_id} Wait"] = pd.Series(col_waits)

    # Display
    df = pd.DataFrame(schedule_data).fillna("")
    display(df)

    # CSV Block
    print("\n" + "="*40)
    print("  COPY FOR SPREADSHEET (CSV)")
    print("="*40)
    print(df.to_csv(index=False, sep=','))

    # 2. CREATE DATAFRAME
    df = pd.DataFrame(schedule_data)

    # Fill empty cells (if one route is shorter than the other)
    df = df.fillna("")

    # Display nicely in Colab
    display(df)


def main():

    data = create_data_model()

    # Create the routing index manager
    manager = pywrapcp.RoutingIndexManager(
        len(data["time_matrix"]), data["num_vehicles"], data["depot"]
    )

    # Create Routing Model
    routing = pywrapcp.RoutingModel(manager)

    # Return the travel time between the two nodes
    def time_callback(from_index, to_index):
        # Convert from routing variable Index to time matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data["time_matrix"][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(time_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Configure Time Dimension
    time = "Time"
    routing.AddDimension(
        transit_callback_index,
        72000,  # allow waiting time
        72000,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time,
    )
    time_dimension = routing.GetDimensionOrDie(time)

    # Add time window constraints for each location except depot
    for location_idx, time_window in enumerate(data["time_windows"]):
        if location_idx == data["depot"]:
            continue
        index = manager.NodeToIndex(location_idx)
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])

    # Add time window constraints for each vehicle start node
    depot_idx = data["depot"]
    for vehicle_id in range(data["num_vehicles"]):
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(
            data["time_windows"][depot_idx][0], data["time_windows"][depot_idx][1]
        )

    # Instantiate route start and end times to produce feasible times
    for i in range(data["num_vehicles"]):
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.Start(i))
        )
        routing.AddVariableMinimizedByFinalizer(time_dimension.CumulVar(routing.End(i)))

    # penalty for dropping locations if the solution is impossible
    penalty = 1000000
    for node in range(1, len(data["time_matrix"])):
        routing.AddDisjunction([manager.NodeToIndex(node)], penalty)

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.time_limit.seconds = 60
    search_parameters.log_search = True
    #First Search Strategy
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.GLOBAL_CHEAPEST_ARC
    )
    #Local Search Metaheuristic Strategy
    search_parameters.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    )

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if solution:
        print_solution_with_slack(data, manager, routing, solution)
    else:
        print ("No Solution found")

main()